### ISSUE TITLE
multiple methods tables found for ‘splitAsList’ when loading DelayedArray

### ISSUE THREAD

**Issue by ngolan1** [Bioconductor/DelayedArray#45] opened 2019-06-13 17:19 UTC
Hello,

I'm currently trying to use your package; however, I keep getting the following error upon installation: 
Warning message:
multiple methods tables found for ‘splitAsList’

Can you please advise?
Thanks!

**Comment by PeteHaitch** [comment] 2019-06-13 21:55
How are you installing? Please post the code you are running and the output of `BiocManager::valid()`.

**Comment by ngolan1** [comment] 2019-06-13 22:08
Thanks for the quick reply. Here is my installation code:

BiocManager::install("DelayedArray")
Bioconductor version 3.10 (BiocManager 1.30.4), R 3.6.0 (2019-04-26)
Installing package(s) 'DelayedArray'
trying URL 'https://bioconductor.org/packages/3.10/bioc/bin/windows/contrib/3.6/DelayedArray_0.11.0.zip'
Content type 'application/zip' length 2230672 bytes (2.1 MB)
downloaded 2.1 MB

package ‘DelayedArray’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\noago\AppData\Local\Temp\Rtmpgv4X7v\downloaded_packages

> BiocManager::valid()

* sessionInfo()

R version 3.6.0 (2019-04-26)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 17763)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
 [1] splines   stats4    parallel  stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] monocle_2.13.0      DDRTree_0.1.5       irlba_2.3.3         VGAM_1.1-1          ggplot2_3.1.1       Biobase_2.45.0     
[7] BiocGenerics_0.31.4 Matrix_1.2-17       Seurat_3.0.1.9020  

loaded via a namespace (and not attached):
  [1] Rtsne_0.15           colorspace_1.4-1     ggridges_0.5.1       rprojroot_1.3-2      fs_1.3.1             rstudioapi_0.10     
  [7] listenv_0.7.0        npsurv_0.4-0         remotes_2.0.4        ggrepel_0.8.1        codetools_0.2-16     R.methodsS3_1.7.1   
 [13] docopt_0.6.1         lsei_1.2-0           pkgload_1.0.2        jsonlite_1.6         ica_1.0-2            cluster_2.0.8       
 [19] png_0.1-7            R.oo_1.22.0          pheatmap_1.0.12      sctransform_0.2.0    BiocManager_1.30.4   compiler_3.6.0      
 [25] httr_1.4.0           backports_1.1.4      assertthat_0.2.1     lazyeval_0.2.2       limma_3.41.3         cli_1.1.0           
 [31] htmltools_0.3.6      prettyunits_1.0.2    tools_3.6.0          rsvd_1.0.1           igraph_1.2.4.1       gtable_0.3.0        
 [37] glue_1.3.1           RANN_2.6.1           reshape2_1.4.3       dplyr_0.8.1          Rcpp_1.0.1           slam_0.1-45         
 [43] gdata_2.18.0         ape_5.3              nlme_3.1-139         gbRd_0.4-11          lmtest_0.9-37        stringr_1.4.0       
 [49] globals_0.12.4       ps_1.3.0             gtools_3.8.1         devtools_2.0.2       future_1.13.0        MASS_7.3-51.4       
 [55] zoo_1.8-6            scales_1.0.0         RColorBrewer_1.1-2   curl_3.3             memoise_1.1.0        reticulate_1.12     
 [61] pbapply_1.4-0        gridExtra_2.3        fastICA_1.2-1        stringi_1.4.3        desc_1.2.0           caTools_1.17.1.2    
 [67] densityClust_0.3     pkgbuild_1.0.3       bibtex_0.4.2         matrixStats_0.54.0   Rdpack_0.11-0        SDMTools_1.1-221.1  
 [73] rlang_0.3.4          pkgconfig_2.0.2      bitops_1.0-6         qlcMatrix_0.9.7      lattice_0.20-38      ROCR_1.0-7          
 [79] purrr_0.3.2          htmlwidgets_1.3      cowplot_0.9.4        processx_3.3.1       tidyselect_0.2.5     plyr_1.8.4          
 [85] magrittr_1.5         R6_2.4.0             gplots_3.0.1.1       combinat_0.0-8       pillar_1.4.1         withr_2.1.2         
 [91] fitdistrplus_1.0-14  survival_2.44-1.1    tibble_2.1.3         future.apply_1.2.0   tsne_0.1-3           crayon_1.3.4        
 [97] KernSmooth_2.23-15   plotly_4.9.0         viridis_0.5.1        usethis_1.5.0        grid_3.6.0           data.table_1.12.2   
[103] FNN_1.1.3            callr_3.2.0          sparsesvd_0.1-4      HSMMSingleCell_1.5.0 metap_1.1            digest_0.6.19       
[109] tidyr_0.8.3          R.utils_2.9.0        munsell_0.5.0        viridisLite_0.3.0    sessioninfo_1.1.1   

Bioconductor version '3.10'

  * 0 packages out-of-date
  * 1 packages too new

create a valid installation with

  BiocManager::install("Seurat", update = TRUE, ask = FALSE)

more details: BiocManager::valid()$too_new, BiocManager::valid()$out_of_date

Warning message:
0 packages out-of-date; 1 packages too new

**Comment by PeteHaitch** [comment] 2019-06-13 22:27
To me, that output shows the package has installed without error or warning.
I don't see 
```R
Warning message:
multiple methods tables found for ‘splitAsList’
```
anywhere in the output?
What code do you run to see the warning?

By the way that's a warning rather than an error (which is not to say it should be ignored!)

**Comment by ngolan1** [comment] 2019-06-13 22:30
Hi Peter, 

I see it when I actually try to use it (i.e. library(DelayedArray). 

I agree that it's a warning and not an error, but it's becoming a problem when I'm trying to install Monocle3 which won't install because of that warning. It may not be an issue on your end, but I thought it was worth asking. 

Thank you for all of your help!

**Comment by PeteHaitch** [comment] 2019-06-13 22:39
The `multiple methods tables found for XXX` warning is one I've seen a bit when working with the development branch of Bioconductor, as you are. 
In this case, it's probably related to this recent change in the **S4Vectors** package (https://github.com/Bioconductor/S4Vectors/commit/09bbc266df3dfbe7b4eae8bfd5abfca399575711).
In my experience, removing and then re-installing the 'core' Bioconductor packages will often fix the issue (e.g., **S4Vectors**, **IRanges**, **BiocGenerics**, ...) 
@mtmorgan or @hpages may know exactly which ones might been to be re-installed.
It's frustrating, but my understanding is the root cause is something way down in how the S4 system is implemented.

I've not seen this warning prevent the installation of a package, however.
I don't have a Windows machine with the development branch installed right now, so I can't offer much more at this moment but I hope this helps.

**Comment by ngolan1** [comment] 2019-06-13 22:41
I'll give that a shot. Thanks again!

**Comment by LTLA** [comment] 2019-06-14 02:37
_SingleCellExperiment_ had that issue for a while, which was fixed by reinstalling its dependencies:

https://support.bioconductor.org/p/101813/#102033

**Comment by hpages** [comment] 2019-06-14 15:21
But did you actually still see the warning after re-installing DelayedArray?

Please show us the output of:
```
BiocManager::install("DelayedArray")
library(DelayedArray)
```

Thanks,
H.

**Comment by hpages** [comment] 2019-06-16 21:51
@ngolan1 I'm assuming that you were able to work this out. Feel free to re-open if you're still having problems with this.

**Closed by hpages** 2019-06-16 21:51 UTC

**Comment by mingy16** [comment] 2019-12-05 03:04
I ran into the same error message, then I checked my version of DelayedArray:
```
packageVersion("DelayedArray")
>'0.10.0.
```
Then I installed the latest version of DelayedArray using:
```
packageUrl<- "http://bioconductor.org/packages/release/bioc/src/contrib/DelayedArray_0.12.0.tar.gz"
install.packages(packageUrl, repos=NULL, type='source')
packageVersion("DelayedArray")
> ‘0.12.0’
```
Then successfully installed monocle3.

**Comment by hpages** [comment] 2019-12-05 05:48
> packageUrl<- "http://bioconductor.org/packages/release/bioc/src/contrib/DelayedArray_0.12.0.tar.gz"
> install.packages(packageUrl, repos=NULL, type='source')

Really?

You should NEVER EVER install a Bioconductor package like this (unless you want to run into all kinds of non-compatibility problems like the "multiple methods tables..." error or other more obscure problems).

**Always** use `BiocManager::install()` instead. See https://bioconductor.org/install/

**Comment by lifengt** [comment] 2020-05-15 19:52
> The `multiple methods tables found for XXX` warning is one I've seen a bit when working with the development branch of Bioconductor, as you are.
> In this case, it's probably related to this recent change in the **S4Vectors** package ([Bioconductor/S4Vectors@09bbc26](https://github.com/Bioconductor/S4Vectors/commit/09bbc266df3dfbe7b4eae8bfd5abfca399575711)).
> In my experience, removing and then re-installing the 'core' Bioconductor packages will often fix the issue (e.g., **S4Vectors**, **IRanges**, **BiocGenerics**, ...)
> @mtmorgan or @hpages may know exactly which ones might been to be re-installed.
> It's frustrating, but my understanding is the root cause is something way down in how the S4 system is implemented.
> 
> I've not seen this warning prevent the installation of a package, however.
> I don't have a Windows machine with the development branch installed right now, so I can't offer much more at this moment but I hope this helps.

Hi,

This is Lifeng.
I did install the flowType recently, and R4.0.0. When I loaded the package

> library(flowType) # the message said
Warning message:
multiple methods tables found for ‘plot’ .

I crossed over this thread, think it may related to my question. 

I tried to re-install the  
> install.packages("BiocGenerics")
Installing package into ‘C:/Users/tianl/Documents/R/win-library/4.0’
(as ‘lib’ is unspecified)
Warning message:
package ‘BiocGenerics’ is not available (for R version 4.0.0) . 

But it said no this package available for R 4. 0.0. 

I am writing for asking what I should do next or what I can do?

Thanks!

**Comment by hpages** [comment] 2020-05-15 21:10
How this has **anything** to do with the DelayedArray package?

You're using Bioconductor packages so please ask on Bioconductor's support site: https://support.bioconductor.org/
But first do your homework and learn the proper way to install Bioconductor packages: https://bioconductor.org/install/

If after this you still need help, make sure you read the Posting Guide before you post your question on Bioconductor's support site. Thanks!

**Comment by lifengt** [comment] 2020-05-16 11:56
I saw this comments under this thread "The multiple methods tables found for XXX warning is one I've seen a bit when working with the development branch of Bioconductor, as you are."

Thanks for your advise, I am a new person, and I will follow the instruction to post in the future.

Thanks again for your suggestions.

Lifeng
